```{r coxtab, cache=cacheon}

survmy <- function(data, time, event, eventname, efvar, ravar = "sos_com_ra") {
  survdata <- data %>% filter(casecontrol == "Case")

  levsef <- levels(pdata %>% pull(!!sym(efvar)))

  out <- data.frame(matrix(NA, ncol = 3 + length(levsef) * 2, nrow = 4))

  out[1, 1] <- eventname

  colnames(out) <- c(
    "Outcome", "Model",
    paste(rep(levsef, 2), rep(levels(data %>% pull(!!sym(ravar))), 2), " RA"),
    "Interaction p"
  )

  ## incidence rate
  out[1, 2] <- "Incidence*"

  for (i in seq_along(levsef)) {
    survdata2 <- survdata %>%
      mutate(eventcount = if_else(!!sym(event) == "Yes", 1, 0)) %>%
      filter(!!sym(efvar) == levsef[i])

    ev <- by(survdata2[, "eventcount"], survdata2[, ravar], sum)
    s <- by(survdata2[, time], survdata2[, ravar], sum) / 365.25
    r <- pois.exact(x = ev, pt = s / 1000)

    out[1, (1 + (i * 2)):(2 + (i * 2))] <- paste0(
      ev, ", ",
      dF(s, dig = 0), ", ",
      dF(r$rate, dig = 1), " (",
      dF(r$lower, dig = 1), "-",
      dF(r$upper, dig = 1), ")"
    )

    # cox regressions
    ## crude
    mod <- coxph(formula(paste0(
      "Surv(", time, ",", event, "=='Yes') ~ ", ravar, " * relevel(", efvar, ", ref = '", levsef[i], "')"
    )),
    data = survdata
    )
    smod <- summary(mod)
    out[2, 2] <- "Crude HR (95% CI), p"
    out[2, (1 + (i * 2)):(2 + (i * 2))] <- c(
      "ref", paste0(
        dF(smod$conf.int[1, 1], dig = 1),
        " (", dF(smod$conf.int[1, 3], dig = 1),
        "-", dF(smod$conf.int[1, 4], dig = 1), "), ",
        dF(smod$coef[1, 5], dig = 3, p = TRUE)
      )
    )

    if (i == 1) {
      out[2, 7] <- last(dF(car::Anova(mod, type = 3)$`Pr(>Chisq)`, dig = 3, p = T))
    }

    ## adj comorbs
    mod <- coxph(formula(paste0(
      "Surv(", time, ",", event, "=='Yes') ~ ", ravar, " * relevel(", efvar, ", ref = '", levsef[i], "') + ",
      paste(modvars1, collapse = " + ")
    )),
    data = survdata
    )

    smod <- summary(mod)
    out[3, 2] <- "Adj age, sex, comorbs HR (95% CI), p"
    out[3, (1 + (i * 2)):(2 + (i * 2))] <- c(
      "ref", paste0(
        dF(smod$conf.int[1, 1], dig = 1),
        " (", dF(smod$conf.int[1, 3], dig = 1),
        "-", dF(smod$conf.int[1, 4], dig = 1), "), ",
        dF(smod$coef[1, 5], dig = 3, p = TRUE)
      )
    )

    if (i == 1) {
      out[3, 7] <- last(dF(car::Anova(mod, type = 3)$`Pr(>Chisq)`, dig = 3, p = T))
    }

    ## adj comorbs + socioec
    mod <- coxph(formula(paste0(
      "Surv(", time, ",", event, "=='Yes') ~ ", ravar, " * relevel(", efvar, ", ref = '", levsef[i], "') + ",
      paste(modvars2, collapse = " + ")
    )),
    data = survdata
    )

    smod <- summary(mod)
    out[4, 2] <- "Adj age, sex, comorbs, socec HR (95% CI), p"
    out[4, (1 + (i * 2)):(2 + (i * 2))] <- c(
      "ref", paste0(
        dF(smod$conf.int[1, 1], dig = 1),
        " (", dF(smod$conf.int[1, 3], dig = 1),
        "-", dF(smod$conf.int[1, 4], dig = 1), "), ",
        dF(smod$coef[1, 5], dig = 3, p = TRUE)
      )
    )

    if (i == 1) {
      out[4, 7] <- last(dF(car::Anova(mod, type = 3)$`Pr(>Chisq)`, dig = 3, p = T))
    }
  }
  return(out)
}
```

```{r coxtab2out, cache=cacheon, dependson="coxtab"}
cvdhosp <- survmy(
  data = pdata %>% filter(shf_location == "Out-patient"),
  efvar = "shf_ef_cat2",
  time = "sos_outtime_deathcvhosphfstrokemi",
  event = "sos_out_deathcvhosphfstrokemi",
  eventname = "CVD/First HF/stroke/MI hospitalization (%)",
  ravar = "sos_com_ra"
)

hfhosp <- survmy(
  data = pdata %>% filter(shf_location == "Out-patient"),
  efvar = "shf_ef_cat2",
  time = "sos_outtime_hosphf",
  event = "sos_out_hosphf",
  eventname = "First HF hospitalization (%)"
)

death <- survmy(
  data = pdata %>% filter(shf_location == "Out-patient"),
  efvar = "shf_ef_cat2",
  time = "sos_outtime_death",
  event = "sos_out_death",
  eventname = "Death (%)"
)

coxoutall <- bind_rows(cvdhosp, hfhosp, death)
colnames(coxoutall) <- c(
  "Outcome", "Model",
  rep(c("No RA", "RA"), 2),
  "Interaction p"
)

write.xlsx(coxoutall, paste0("./output/tabs/coxtab2_out_", Sys.Date(), ".xlsx"), rowNames = FALSE)

myHeader <- c(" " = 1, " " = 1, "<40%" = 2, ">=40%" = 2, " " = 1)
names(myHeader) <- c(" ", " ", "<40%", ">=40%", " ")

footnote(mykable(coxoutall,
  fontsize = 10,
  caption = sanitize_text("Associations between outcomes and prior RA by EF </>=40% - Out-patients")
) %>%
  landscape() %>%
  add_header_above(myHeader),
symbol = c(
  "Incidence = no events, sum py, rate/1000py (95% CI)."
)
)
```

```{r coxtab2blanksensout, cache=cacheon, dependson="coxtab"}
cvdhosp <- survmy(
  data = pdata %>% filter(shf_location == "Out-patient"),
  efvar = "shf_ef_cat2",
  time = "sos_outtime_deathcvhosphfstrokemi",
  event = "sos_out_deathcvhosphfstrokemi",
  eventname = "CVD/First HF/stroke/MI hospitalization (%)",
  ravar = "sos_com_ra_blank6mo"
)

hfhosp <- survmy(
  data = pdata %>% filter(shf_location == "Out-patient"),
  efvar = "shf_ef_cat2",
  time = "sos_outtime_hosphf",
  event = "sos_out_hosphf",
  eventname = "First HF hospitalization (%)",
  ravar = "sos_com_ra_blank6mo"
)

death <- survmy(
  data = pdata %>% filter(shf_location == "Out-patient"),
  efvar = "shf_ef_cat2",
  time = "sos_outtime_death",
  event = "sos_out_death",
  eventname = "Death (%)",
  ravar = "sos_com_ra_blank6mo"
)

coxoutall <- bind_rows(cvdhosp, hfhosp, death)
colnames(coxoutall) <- c(
  "Outcome", "Model",
  rep(c("No RA", "RA"), 2),
  "Interaction p"
)

write.xlsx(coxoutall, paste0("./output/tabs/coxtab2_blank6mo_out_", Sys.Date(), ".xlsx"), rowNames = FALSE)

myHeader <- c(" " = 1, " " = 1, "<40%" = 2, ">=40%" = 2, " " = 1)
names(myHeader) <- c(" ", " ", "<40%", ">=40%", " ")

footnote(mykable(coxoutall,
  fontsize = 10,
  caption = sanitize_text("Associations between outcomes and prior RA with blanking 6 mo by EF </>=40% - Out-patients")
) %>%
  landscape() %>%
  add_header_above(myHeader),
symbol = c(
  "Incidence = no events, sum py, rate/1000py (95% CI)."
)
)
```

```{r coxtabout, cache=cacheon, dependson="coxtab"}
cvdhosp <- survmy(
  data = pdata %>% filter(shf_location == "Out-patient"),
  efvar = "shf_ef_cat",
  time = "sos_outtime_deathcvhosphfstrokemi",
  event = "sos_out_deathcvhosphfstrokemi",
  eventname = "CVD/First HF/stroke/MI hospitalization (%)"
)

hfhosp <- survmy(
  data = pdata %>% filter(shf_location == "Out-patient"),
  efvar = "shf_ef_cat",
  time = "sos_outtime_hosphf",
  event = "sos_out_hosphf",
  eventname = "First HF hospitalization (%)"
)

death <- survmy(
  data = pdata %>% filter(shf_location == "Out-patient"),
  efvar = "shf_ef_cat",
  time = "sos_outtime_death",
  event = "sos_out_death",
  eventname = "Death (%)"
)

coxoutall <- bind_rows(cvdhosp, hfhosp, death)
colnames(coxoutall) <- c(
  "Outcome", "Model",
  rep(c("No RA", "RA"), 3),
  "Interaction p"
)

write.xlsx(coxoutall, paste0("./output/tabs/coxtab_out_", Sys.Date(), ".xlsx"), rowNames = FALSE)

myHeader <- c(" " = 1, " " = 1, "rEF" = 2, "mrEF" = 2, "pEF" = 2, " " = 1)
names(myHeader) <- c(" ", " ", "rEF", "mrEF", "pEF", " ")

footnote(mykable(coxoutall,
  fontsize = 10,
  caption = paste0("Associations between outcomes and prior RA by r/mr/pEF - Out-patients")
) %>%
  landscape() %>%
  add_header_above(myHeader),
symbol = c(
  "Incidence = no events, sum py, rate/1000py (95% CI)."
)
)
```

```{r coxtab2in, cache=cacheon, dependson="coxtab"}
cvdhosp <- survmy(
  data = pdata %>% filter(shf_location == "In-patient"),
  efvar = "shf_ef_cat2",
  time = "sos_outtime_deathcvhosphfstrokemi",
  event = "sos_out_deathcvhosphfstrokemi",
  eventname = "CVD/First HF/stroke/MI hospitalization (%)",
  ravar = "sos_com_ra"
)

hfhosp <- survmy(
  data = pdata %>% filter(shf_location == "In-patient"),
  efvar = "shf_ef_cat2",
  time = "sos_outtime_hosphf",
  event = "sos_out_hosphf",
  eventname = "First HF hospitalization (%)"
)

death <- survmy(
  data = pdata %>% filter(shf_location == "In-patient"),
  efvar = "shf_ef_cat2",
  time = "sos_outtime_death",
  event = "sos_out_death",
  eventname = "Death (%)"
)

coxoutall <- bind_rows(cvdhosp, hfhosp, death)
colnames(coxoutall) <- c(
  "Outcome", "Model",
  rep(c("No RA", "RA"), 2),
  "Interaction p"
)

write.xlsx(coxoutall, paste0("./output/tabs/coxtab2_in_", Sys.Date(), ".xlsx"), rowNames = FALSE)

myHeader <- c(" " = 1, " " = 1, "<40%" = 2, ">=40%" = 2, " " = 1)
names(myHeader) <- c(" ", " ", "<40%", ">=40%", " ")

footnote(mykable(coxoutall,
  fontsize = 10,
  caption = sanitize_text("Associations between outcomes and prior RA by EF </>=40% - In-patients")
) %>%
  landscape() %>%
  add_header_above(myHeader),
symbol = c(
  "Incidence = no events, sum py, rate/1000py (95% CI)."
)
)
```

```{r coxtab2blanksensin, cache=cacheon, dependson="coxtab"}
cvdhosp <- survmy(
  data = pdata %>% filter(shf_location == "In-patient"),
  efvar = "shf_ef_cat2",
  time = "sos_outtime_deathcvhosphfstrokemi",
  event = "sos_out_deathcvhosphfstrokemi",
  eventname = "CVD/First HF/stroke/MI hospitalization (%)",
  ravar = "sos_com_ra_blank6mo"
)

hfhosp <- survmy(
  data = pdata %>% filter(shf_location == "In-patient"),
  efvar = "shf_ef_cat2",
  time = "sos_outtime_hosphf",
  event = "sos_out_hosphf",
  eventname = "First HF hospitalization (%)",
  ravar = "sos_com_ra_blank6mo"
)

death <- survmy(
  data = pdata %>% filter(shf_location == "In-patient"),
  efvar = "shf_ef_cat2",
  time = "sos_outtime_death",
  event = "sos_out_death",
  eventname = "Death (%)",
  ravar = "sos_com_ra_blank6mo"
)

coxoutall <- bind_rows(cvdhosp, hfhosp, death)
colnames(coxoutall) <- c(
  "Outcome", "Model",
  rep(c("No RA", "RA"), 2),
  "Interaction p"
)

write.xlsx(coxoutall, paste0("./output/tabs/coxtab2_blank6mo_in_", Sys.Date(), ".xlsx"), rowNames = FALSE)

myHeader <- c(" " = 1, " " = 1, "<40%" = 2, ">=40%" = 2, " " = 1)
names(myHeader) <- c(" ", " ", "<40%", ">=40%", " ")

footnote(mykable(coxoutall,
  fontsize = 10,
  caption = sanitize_text("Associations between outcomes and prior RA with blanking 6 mo by EF </>=40% - In-patients")
) %>%
  landscape() %>%
  add_header_above(myHeader),
symbol = c(
  "Incidence = no events, sum py, rate/1000py (95% CI)."
)
)
```

```{r coxtabin, cache=cacheon, dependson="coxtab"}
cvdhosp <- survmy(
  data = pdata %>% filter(shf_location == "In-patient"),
  efvar = "shf_ef_cat",
  time = "sos_outtime_deathcvhosphfstrokemi",
  event = "sos_out_deathcvhosphfstrokemi",
  eventname = "CVD/First HF/stroke/MI hospitalization (%)"
)

hfhosp <- survmy(
  data = pdata %>% filter(shf_location == "In-patient"),
  efvar = "shf_ef_cat",
  time = "sos_outtime_hosphf",
  event = "sos_out_hosphf",
  eventname = "First HF hospitalization (%)"
)

death <- survmy(
  data = pdata %>% filter(shf_location == "In-patient"),
  efvar = "shf_ef_cat",
  time = "sos_outtime_death",
  event = "sos_out_death",
  eventname = "Death (%)"
)

coxoutall <- bind_rows(cvdhosp, hfhosp, death)
colnames(coxoutall) <- c(
  "Outcome", "Model",
  rep(c("No RA", "RA"), 3),
  "Interaction p"
)

write.xlsx(coxoutall, paste0("./output/tabs/coxtab_in_", Sys.Date(), ".xlsx"), rowNames = FALSE)

myHeader <- c(" " = 1, " " = 1, "rEF" = 2, "mrEF" = 2, "pEF" = 2, " " = 1)
names(myHeader) <- c(" ", " ", "rEF", "mrEF", "pEF", " ")

footnote(mykable(coxoutall,
  fontsize = 10,
  caption = paste0("Associations between outcomes and prior RA by r/mr/pEF - In-patients")
) %>%
  landscape() %>%
  add_header_above(myHeader),
symbol = c(
  "Incidence = no events, sum py, rate/1000py (95% CI)."
)
)
```
